timholy/CodeTracking.jl

- .travis.yml
- Project.toml
- README.md
- src/CodeTracking.jl
- src/data.jl
- src/utils.jl
- test/runtests.jl
- test/script.jl
Here's the beginning of real forward-movement on this package. The proposed public API is in `CodeTracking.jl` itself, the other files are internal. Comments welcome.
> Implement an initial API

- REQUIRE
I failed to notice that the REQUIRE file had specified `julia 1.1-`. But the package works fine on `1.x`.
> Relax Julia version requirement

- src/CodeTracking.jl
- test/runtests.jl
This was throwing errors for methods defined at the REPL.
> Handle case where find_source_file fails

- README.md
- src/CodeTracking.jl
- src/utils.jl
- test/runtests.jl
This allows one to find the methods defined by a particular block of code. One subtlety here is that multiple methods might be defined if the file/line combination points to a method with default arguments, keyword arguments, and the like. Note that not all of these methods are guaranteed to even have the same name.
I also contemplated calling this `methods_at`, but that can be obtained from `signatures_at` followed by call(s) to `which` (or better, `whichtt` in JuliaInterpreter). Since `which` is slow, I thought it would be better to return just the most essential information.
Closes #3.
> Implement signatures_at

- src/CodeTracking.jl
Revise's `includet` associates these with Main and via absolute path
> Support files associated with Main

- src/CodeTracking.jl
https://github.com/JuliaDebug/JuliaInterpreter.jl/issues/144#issue-421119275
>  Try harder to find the true path of a method 

- src/CodeTracking.jl
- test/runtests.jl
This guards against busted callbacks
> Run callbacks inside try/catch

- src/CodeTracking.jl
- src/utils.jl
- test/runtests.jl
Fixes https://github.com/JuliaDebug/JuliaInterpreter.jl/issues/150
> File location info for macro expansions.

- src/CodeTracking.jl
- test/runtests.jl
This allows Revise to prevent re-execution of `method_lookup_callback[]` by indicating that the method definition is not available.
> Allow marking of methods as missing

- src/CodeTracking.jl
- src/utils.jl
- test/runtests.jl
This may require https://github.com/timholy/Revise.jl/pull/243 to actually work (not certain, it might be OK without).
> signatures_at support for Base, stdlibs, and methods defined at the REPL

- src/CodeTracking.jl
- test/runtests.jl
>  Use abspath on filenames 

- src/CodeTracking.jl
- test/runtests.jl
- test/script.jl
The String variant of `definition` has the ability to back up in the source file to also extract the signature. As a consequence, it may be unclear how the first line of the string corresponds to the output of `whereis`. To resolve the uncertainty, return the first source line as a second argument from `definition(::Method, String)`.
This is a breaking change; this will become CodeTracking v0.4.0.
> Change the API on `definition(::Method, String)`

- .travis.yml
- src/CodeTracking.jl
- src/utils.jl
- test/runtests.jl
Argh, in fixing #23 I broke other stuff. So we should start running the Revise tests here.
Also fixes #28.
>  Avoid abspath for REPL-defined "paths" 

- src/utils.jl
Looks like a typo from a refactoring. A test is being added to Revise.
> Fix `definition(String, m)` for methods defined at the REPL

- src/CodeTracking.jl
- src/utils.jl
- test/runtests.jl
- test/script.jl
This will run into problems for macros that create methods, but that's problematic anyway.
Fixes #31
> Strip macros in `definition(String, m)`

- src/CodeTracking.jl
The signature is the same, but the "file" may be different. Consequently we shouldn't do signature-based lookup, we should simply look it up again.
A test is already prepared for Revise, will be submitted after this gets tagged.
> Force fresh lookup of methods defined at the REPL (fixes #32)

- appveyor.yml
- src/CodeTracking.jl
- test/runtests.jl
Is this change sufficiently breaking that we need to bump the minor version number? (We don't have the equivalent of `Pkg.dependents` yet, do we?)
> Strip final line endings (fix #42)

- src/utils.jl
- test/runtests.jl
> fix no arg macros in function defs

- src/CodeTracking.jl
- test/runtests.jl
>  Return `nothing` for methods with line == 0

- src/utils.jl
Fixes https://github.com/JuliaDebug/JuliaInterpreter.jl/issues/386
> use a non throwing version of isfile

- README.md
- src/CodeTracking.jl
- test/runtests.jl
Fixes #46.
I decided to keep `definition` as it also provides line number information. We could unexport `definition`, of course, as a breaking change. I intend to go to 1.0 once #55 is resolved and a compatible version of Revise is released, so we'll be making at least one breaking release soon anyway. And if we decide to unexport `definition`, we could consider doing that separately with a 0.6 release.
> Add code_expr & code_string

- Project.toml
- src/CodeTracking.jl
Fixes #55
I plan to release this as 1.0 after this merges, ref https://github.com/timholy/CodeTracking.jl/pull/58#issue-410695137.
> Support multiple definitions for a particular signature

- src/utils.jl
- test/runtests.jl
- test/script.jl
See the added tests for MWEs when the current code would fail to find the method body properly.
> fix some issues with module prefixed functions

- src/CodeTracking.jl
- test/runtests.jl
Updates for some great work by @KristofferC:
- TOMLCache (https://github.com/JuliaLang/julia/pull/37906)
- Elimination of `__PackagePrecompilationStatementModule` (https://github.com/JuliaLang/julia/pull/37918)
Closes #68
> Fixes for nightly

- src/CodeTracking.jl
This and related PRs are intended to avoid warnings that would have
otherwise occurred when running Julia PR37193 as test-revise.
> Improve inference for LineInfoNodes

- src/CodeTracking.jl
- src/utils.jl
- test/runtests.jl
This also exposed some previously-untested functionality on Julia 1.0,
in particular the absence of `splitpath` on Julia 1.0.
I'm not sure what could have changed, but maybe the improvement
to `checkname` ended up hitting new code paths on 1.0?
> Get tests working on recent Julia versions

- .github/workflows/ci.yml
- test/Project.toml
- test/runtests.jl
> Run tests with and without Revise

- src/utils.jl
- test/runtests.jl
- test/script.jl
> Fix `definition` for return-type annotations

- src/CodeTracking.jl
- test/runtests.jl
As suggested by @KristofferC in https://github.com/JuliaDocs/Documenter.jl/issues/1779#issuecomment-1066713491. This is related to problems using CodeTracking.jl with Documenter.jl (see https://github.com/JuliaDocs/Documenter.jl/issues/1779) or Jupyter notebooks (see https://github.com/timholy/CodeTracking.jl/issues/51). Instead of throwing an exception, `code_string` now returns `nothing` if `definition` returns `nothing`. This makes it easier to handle such a problematic case by the user.
Since the issue only appears in these on-standard environments, I do not really know a nice way to integrate an appropriate test in the current framework.
> let code_string return nothing if definition returns nothing

- src/CodeTracking.jl
`CodeTracking.whereis` currently assumes that the only thing a LineNumberNode can change is the line within the function, but that the file is always the same as the file that the method was defined in (unless there's a macro expansion). That is true for methods that come from the parser, but not necessarily for those that were generated programatically, causing `whereis` to return an incorrect file with the correct line number, causing dowstream issues like https://github.com/JuliaDebug/CassetteOverlay.jl/issues/18.
> Don't assume that a method body's file is always the same as the def

- .github/workflows/ci.yml
- Project.toml
- src/utils.jl
- test/runtests.jl
- improve coverage, simplify some tests;
- update `ci.yml` (use `action@latest` where possible, and `julia-actions/cache@v1`);
- julia: drop `1.0`, min is now `1.6` LTS (`JuliaInterpreter`, `Cthulhu`, `Debugger`, `Revise` ✔: this will require bump to `1.1.0`), drop `1.0` compat code;
- remove unnecessary `joinpath` in `utils.jl` (`abspath` already joins paths);
- fix `@test occursin(Sys.STDLIB, whereis(m)[1])` on a local julia build where the source files are available locally on the fs.
> bump cov - update `ci.yml` - fix tests on local build

- Project.toml
- src/utils.jl
- test/runtests.jl
Because IdDict's `setindex!` uses `@nospecialize` on both the key and
value, it makes callers vulnerable to invalidation. These convenience
utilities allow callers to insulate themselves from invalidation.
These will be used by Revise.
> Add invalidation-insulating accessors

- .github/workflows/ci.yml
- src/utils.jl
- test/runtests.jl
- test/script.jl
> Support anonymous functions

- src/CodeTracking.jl
- test/runtests.jl
Keyword dispatch methods went away in Julia 1.9, replaced by the
generic `kwcall`. In #102 I disabled the corresponding test.
That was misguided because we still want to be able to recover the
source definition, regardless of the details of the underlying
implementation.
> Support `Core.kwcall`

- src/CodeTracking.jl
- src/utils.jl
- test/runtests.jl
- test/script.jl
These get an extra `:toplevel` Expr wrapper, which we need to strip.
> Handle method defs that end in a semicolon

- Project.toml
- README.md
- src/CodeTracking.jl
- src/utils.jl
- test/runtests.jl
- test/script.jl
While working on TypedSyntax.jl it became apparent that CodeTracking
sometimes returns spurious results. At least some of these arise from
the recent support of anonymous functions, #102, which might in
retrospect have been ill-considered. Rather than back that change
out, this adopts a different resolution: validate the hits more
carefully.  The primary mechanism introduced here is to match not just
the function name, but also the argument names. This can work even for
anonymous functions, so we do not need to drop support for them.
This also adds quite a few new tests. These additions would have
passed before, but they proved valuable to ensure that the new
argname-matching works sufficiently well.
On TypedSyntax's "exhaustive.jl" test, this brings the
number of failed cases …
> Also match argnames to validate methods

- src/utils.jl
- test/runtests.jl
- test/script.jl
If an arg is interpolated and has a splat, we can't be sure that
arguments will be aligned anymore. Terminate the validation.
Improves #110 and the fix for
https://github.com/JuliaDebug/Cthulhu.jl/issues/425
> Also handle splats in interpolated args

- src/utils.jl
> Eliminate piracy of `convert(LineNumberNode, ::LineInfoNode)`

- src/CodeTracking.jl
- test/runtests.jl
This fixes the `NamedTuple` example in #115, the problem was that the definition,
```jl
eval(Core, :(NamedTuple{names,T}(args::T) where {names, T <: Tuple} =
$(Expr(:splatnew, :(NamedTuple{names,T}), :args))))
```
has the beginning of the function definition on the same line as the `eval`.
> Fix lookup for methods defined inline with eval

- src/utils.jl
- test/runtests.jl
The problem here was that `strip_gensym(meth.name) = Array` but `fname = (Array{T, N} where T)`, so I added some code to match on the `where` to simplify `fname`.
> Fix `Array` example in #115

- src/CodeTracking.jl
- test/runtests.jl
- test/script.jl
Sorry, I left these changes stashed by accident. I've added a test now to catch this.
> Fix previous pr #116

- src/CodeTracking.jl
- test/runtests.jl
- test/script.jl
It would be nice to have a more realistic reproducer, but hopefully this suffices.
Fixes #124
> Check for unexpected EOF in `definition`

- src/utils.jl
- test/runtests.jl
fixes JuliaDebug/Cthulhu.jl#583
> `strip_gensym`: handle unicode correctly

- .github/workflows/ci.yml
- src/utils.jl
- test/runtests.jl
- test/script.jl
Also fixes an error exposed in the "exhausive.jl" test in TypedSyntax, https://github.com/JuliaDebug/Cthulhu.jl/pull/585
> Update implementation and tests for Julia 1.10, 1.11

- src/utils.jl
This allows us to automatically get new functionality like https://github.com/JuliaLang/julia/pull/57274.
> Use upstream functionality for fixing stdlib paths

- .github/workflows/ci.yml
- src/CodeTracking.jl
- src/utils.jl
- test/runtests.jl
https://github.com/JuliaLang/julia/pull/52415 introduced a fundamental
change in how line information is encoded. Because this package delves
into internals, there were a couple tests that failed on Julia 1.12+.
This adds a utility, `CodeTracking.linetable_scopes`, that makes it
easier to work with the new representation across Julia versions.
This may be useful in fixing some JuliaInterpreter issues.
CC @aviatesk, @vtjnash
> Fix tests for inverted linetable

- Project.toml
- src/utils.jl
> Generalize the "method" for `linetable_scopes`

- src/utils.jl
In take 1 I removed the `maybe_fixup_stdlib_path` but that is actually used by e.g. JuliaInterpreter.  This should fx the Revise errors that take 1 encountered.
> Use upstream functionality for fixing stdlib paths (take 2)

- .github/workflows/ci.yml
- Project.toml
- README.md
- src/CodeTracking.jl
- src/utils.jl
- test/runtests.jl
Modify the format of `method_info` to have it keyed by `mt::Union{Nothing, MethodTable} => sig` pairs instead of `sig`.
This allows Revise and other packages to lookup `method_info` scoped by an external method table, if any (a value of `nothing` representing the internal method table).
An alternative design would be use two dictionaries, where the current `sig => [(lnn, ex)...]` mapping would be a value of an outer `mt => info` mapping. I went with keeping a single dictionary (but modifying its key format) for simplicity, but I am open to other designs.
> Add method table as key for `method_info`

- Project.toml
#140 introduced a breaking change to the `method_info` data structure, requiring a breaking release.
We had thought of deferring this breaking release until a new change to Revise that may require breaking changes. See https://github.com/timholy/Revise.jl/pull/904#issuecomment-2959251528 for context on the opening of this PR.
> Tag breaking release
